version: "3.8"

services:
  minecraft-events-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env.common
        required: true
      - path: ./.env.development
        required: true
    volumes:
      - /app/node_modules
    working_dir: /app
    command: pnpm run start:dev
    restart: unless-stopped
