version: "3.8"

services:
  minecraft-events-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - path: ./common.env
        required: true
      - path: ./local.env
        required: true
    volumes:
      - ../:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm run start:dev
    restart: unless-stopped
