version: "3.8"

name: streaming-events

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: streaming-events-backend
    ports:
      - "3000:3000"
    env_file:
      - path: ./.env.common
        required: true
      - path: ./.env.development
        required: true
      - path: ./.env.database
        required: true
    volumes:
      - /app/node_modules
    working_dir: /app
    command: pnpm run start:dev
    restart: unless-stopped
